// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldvyuxvzibpwacumzbgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkdnl1eHZ6aWJwd2FjdW16Ymd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDg0MTAsImV4cCI6MjA3MjEyNDQxMH0.wbZLqxaubgKnYZ3EsDJ-WJ4FlQdmqNR6DpIXjzeWa9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});